apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: task-run-kubectl
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  description: |
    This task is used to run kubectl commands in our ps-dev cluster
  params:
    - name: kubectlParameters 
      type: string
      description: The parameters for the kubectl command
    - name: image
      default: gcr.io/cloud-builders/kubectl@sha256:8ab94be8b2b4f3d117f02d868b39540fddd225447abf4014f7ba4765cb39f753 #image is huge
      description: kubectl wrapper image # We need to update the default one for sure
  steps:
    - name: install-entando
      image: $(params.image)
      script: |
        #!/usr/bin/env bash
        set -x 
        kubectl $(params.kubectlParameters)        
