name: Merge any release branch to main
run-name: ${{ github.actor }} has merged pr in the release branch
on:
 push:
   branches:
     - 'release/**'

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge release -> main
        uses: devmax/merge-branch@master
        with:
          type: now
          target_branch: main
          message: Merge release into main
          github_token: ${{ secrets.GITHUB_TOKEN }}
